### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by rhysperry111** [Maxr1998/SimpleShutdownDialog#1]
I am currently on a train and so do not have access to a system to screenshot from, but I think it would be helpful to have a screenshot

**Comment by Maxr1998** [comment]
**Screenshot:**
![SimpleShutdownDialog](https://user-images.githubusercontent.com/5903699/63291244-7478dd00-c2c3-11e9-99f3-ac8aeffdc350.png)

Uploaded it into this issue, so that I can reference it from my README. I pushed it a a few moments ago.
